env:
  browser: true
  commonjs: true
  es6: true
  node: true
  jest: true
settings:
  react:
    version: 16.6.1
extends:
  - eslint:recommended
parserOptions:
  ecmaFeatures:
    jsx: false
  ecmaVersion: 2018
  sourceType: module
